/**
* @author 
* @description : constant file holds all constants required to integrate Mock Adapter for OFAC Check  .
*/ 
global class OFACMockAdapterConstants {

    

    //Borrower Details Alias

    global static String BORROWER = 'Borrower';
    global static String BORROWER_FIRST_NAME = 'borrowerFirstName';
    global static String BORROWER_LAST_NAME = 'borrowerLastName';
    global static String BORROWER_SSN = 'borrowerSSN';
    global static String BORROWER_STREET = 'borrowerAddress';
	global static String BORROWER_STATE = 'borrowerState';
   	global static String BORROWER_POSTALCODE = 'borrowerPostalCode';
  	global static String BORROWER_BIRTH_DATE = 'borrowerBirthdate';
  	global static String RESPONSE_FAILURE_STATUS = 'Failure';
  	global static String RESPONSE_SUCCESS_STATUS = 'Success';
    global static String ADAPTER_NAME = 'OFACMockIntegrationAdapter';   

    

}